# Root Hugo Configuration
#
# For theme-specific settings, see: `config/_default/`
# Documentation: https://alpha.oxypteros.com/docs/config/hugo-toml

baseURL = "https://alpha-starter.pages.dev" # Replace with production URL
title = "万里开霁"
theme = "alpha"
#timeZone = "Europe/Rome"


# Tailwind Integration (Build Options) 
# Note: Enable the following only if you are using Tailwind CSS with this 
# project.
# For setup instructions, see:
# https://alpha.oxypteros.com/docs/developing-alpha/tailwind

#[build]
#  [build.buildStats]
#    enable = true
#  [[build.cachebusters]]
#    source = 'assets/notwatching/hugo_stats\.json'
#    target = 'css'
#  [[build.cachebusters]]
#    source = '(postcss|tailwind)\.config\.js'
#    target = 'css'
#  [[module.mounts]]
#    source = 'assets'
#    target = 'assets'
#  [[module.mounts]]
#    disableWatch = true
#    source = 'hugo_stats.json'
#    target = 'assets/notwatching/hugo_stats.json'

defaultContentLanguage = "zh-CN"
defaultContentLanguageInSubdir = false 

[languages]
  [languages.zh-CN]
    title = "万里开霁"
    languageName = "简体中文"
    languageCode = "zh-CN"
    weight = 1  # 主语言权重
    hasCJKLanguage = true
  [languages.en]
    title = "MY BLOG"
    languageCode = "en"
    languageName = "English"
    hasCJKLanguage = true
    weight = 2

